apiVersion: apps/v1
kind: Deployment
metadata:
  name: jtq
  namespace:
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jtq
  template:
    metadata:
      labels:
        app: jtq
    spec:
      containers:
        - name: back-end
          image: be-jtq:latest
          ports:
            - containerPort: 8081
