apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: jtq
spec:
  selector:
    app: jtq-be # Nombre pod de deployment.yml
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081 # Puerto interno del contenedor del backend
      targetPort: 8081 # Puerto en el contenedor del backend
