apiVersion: apps/v1
kind: Deployment
metadata:
  name: jtq-fe
  namespace: jtq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jump-the-queue
  template:
    metadata:
      labels:
        app: jump-the-queue
    spec:
      containers:
        - name: front-end
          image: ghcr.io/spiquera/jump-the-queue:front-end
          ports:
            - containerPort: 80
