apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: jtq
spec:
  selector:
    app: jtq-fe # Nombre pod de deployment.yml
  type: NodePort
  ports:
    - protocol: TCP
      port: 80 # Puerto interno del contenedor del frontend
      targetPort: 80 # Puerto en el contenedor del frontend
