name: 2. Develop Change (create docker images, push to github)
on:
  push:
    branches:
      - develop

jobs:
  build-and-push-docker:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push front image
        uses: docker/build-push-action@v3
        with:
          context: ./angular
          file: ./angular/dockerfile
          push: true
          tags: develop-front:latest

      - name: Build and push back image
        uses: docker/build-push-action@v3
        with:
          context: ./java
          file: ./java/dockerfile
          push: true
          tags: develop-back:latest
