# Pipeline para build-lint-test-SonarCloud cuando haya una PR a master (test opening a PR from develop to master)
#

name: Pull-request

on:
  pull_request:
    types: [opened, synchronize]
    branches: ["master"]

jobs:
  angular:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.pull_request.changed_files, 'angular/') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: ./angular
        run: |
          yarn install
      - name: Compile application
        working-directory: ./angular
        run: |
          yarn build
      - name: Execute linter
        working-directory: ./angular
        run: |
          yarn lint
      - name: Execute tests
        working-directory: ./angular
        run: |
          yarn test --watch=false --code-coverage
      - name: SonarCloud Scan Front
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: angular/.
          args: -Dsonar.projectKey=spiquera_jump-the-queue
            -Dsonar.organization=spiquera
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  java:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event.pull_request.changed_files, 'java/') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: "11"
      - name: Build project with Maven
        working-directory: ./java/jtqj
        run: |
          mvn install
      - name: Test back
        working-directory: ./java/jtqj
        run: |
          mvn test
      - name: SonarCloud Scan Back
        continue-on-error: true
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: java/.
          args: -Dsonar.projectKey=spiquera_jump-the-queue
            -Dsonar.organization=spiquera
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
